steps:
  - name: node:10.10.0
    entrypoint: npm
    args:
    - install

  - name: node:10.10.0
    entrypoint: npm
    args:
    - run
    - build

  - name: gcr.io/cloud-builders/gcloud
    args:
    - functions
    - deploy
    - subscribe
    - --stage-bucket=selmertsx-sample-bucket
    - --trigger-topic=cloud-builds
    - --source=.build/
    - --runtime=nodejs8
