steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - kms
    - decrypt
    - --ciphertext-file=.env.yaml.enc
    - --plaintext-file=.env.yaml
    - --location=global
    - --keyring=sample-keyrings
    - --key=sample-key
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - beta
    - functions
    - deploy
    - subscribe
    - --stage-bucket=selmertsx-sample-bucket
    - --trigger-topic=cloud-builds
    - --env-vars-file=.env.yaml
