steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud kms decrypt --ciphertext-file=.env.json.enc --plaintext-file=.env.json --location=global --keyring=sample-keyrings --key=sample-key
        gcloud kms decrypt --ciphertext-file=keyfile.json.enc --plaintext-file=keyfile.json --location=global --keyring=sample-keyrings --key=sample-key
  - name: node:10.10.0
    entrypoint: npm
    args:
      - ['install', '--production']
      - ['run', 'deploy']
