# see:
# https://serverless.com/framework/docs/providers/google/
# https://serverless.com/framework/docs/providers/google/guide/variables/

service: cloud-function-sample

provider:
  name: google
  region: asia-northeast1
  runtime: nodejs8
  credentials: ./deploy.json
  project: ${file(./.env.json):PROJECT}
  memorySize: 128
plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  subscribeFunction:
    handler: subscribe
    events:
    - event:
        eventType: providers/cloud.pubsub/eventTypes/topic.publish
        resource: projects/${file(./.env.json):PROJECT}/topics/cloud-builds
