# see: https://serverless.com/framework/docs/providers/google/

service: cloud-function-sample

provider:
  name: google
  region: asia-northeast1
  runtime: nodejs8
  credentials: ./keyfile.json
  project: ${env:PROJECT}
  memorySize: 128
plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  subscribeFunction:
    handler: subscribe
    events:
    - event:
        eventType: providers/cloud.pubsub/eventTypes/topic.publish
        resource: projects/${env:PROJECT}/topics/cloud-builds
